// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mztdnkhdbrpgolrpjsjf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im16dGRua2hkYnJwZ29scnBqc2pmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4ODE1MTAsImV4cCI6MjA3MDQ1NzUxMH0.Q8ngLFdXyMd2iJEstRuOlJrBEnpNkgUV_O7nOenAYao";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});